<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Advice Rule</name>
  <uuid>5ee2fcf9-07ed-4943-b8bd-d001004db1a7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if Name is defined
then 
set decision to "Hello " + Name + "!" ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
